# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'StudyBuddySwiftUi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StudyBuddySwiftUi

  target 'StudyBuddySwiftUiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StudyBuddySwiftUiUITests' do
    inherit! :search_paths
    # Pods for testing
  end


pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'MessageKit'
pod 'IQKeyboardManagerSwift', '6.5.4'

end

